# Generated by Django 5.2.5 on 2025-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="picture",
            field=models.ImageField(null=True, upload_to="products/images/"),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
