# Generated by Django 5.2.5 on 2025-09-09 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_main", "0002_product_picture_delete_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
