# Generated by Django 5.2.5 on 2025-09-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_main", "0004_coupon_order_coupon_shippingaddress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="score",
        ),
    ]
