# Generated by Django 5.2.5 on 2025-10-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_main", "0005_remove_product_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В обработке"),
                    ("processing", "Обрабатывается"),
                    ("shipped", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменен"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
