# Generated by Django 5.2.5 on 2025-11-10 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0006_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('signup', 'Регистрация'), ('order_created', 'Создан заказ'), ('order_updated', 'Обновлен заказ'), ('product_viewed', 'Просмотр товара'), ('cart_added', 'Добавлено в корзину'), ('cart_removed', 'Удалено из корзины'), ('review_created', 'Создан отзыв'), ('coupon_applied', 'Применен купон'), ('page_visited', 'Посещение страницы')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='shop_main.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='shop_main.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='shop_main_l_created_d0072e_idx'), models.Index(fields=['user', '-created_at'], name='shop_main_l_user_id_1afefd_idx'), models.Index(fields=['action', '-created_at'], name='shop_main_l_action_44d12d_idx')],
            },
        ),
    ]
