# Generated by Django 5.2.5 on 2025-11-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0007_logentry'),
    ]

    operations = [
        migrations.RunSQL(
            # Удаляем триггер и функцию check_order_dates
            # Сначала удаляем триггер, потом функцию (или используем CASCADE)
            sql=[
                "DROP TRIGGER IF EXISTS order_dates_check ON shop_main_order;",
                "DROP TRIGGER IF EXISTS check_order_dates_trigger ON shop_main_order;",
                "DROP FUNCTION IF EXISTS check_order_dates() CASCADE;",
            ],
            reverse_sql=[
                # В обратном направлении ничего не делаем, так как триггер был ошибочным
            ],
        ),
    ]
